# Generated by Django 2.2 on 2021-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdata',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
