# Generated by Django 2.2 on 2021-10-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0002_auto_20211027_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdata',
            name='image',
            field=models.ImageField(default='images/none/noimg.jpg', upload_to='images'),
        ),
    ]
